[package]
name = "nvui-nvim-client"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
rmp = { workspace = true }
rmp-serde = { workspace = true }
rmpv = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
dashmap = { workspace = true }
flume = { workspace = true }
arc-swap = { workspace = true }
serde_tuple = { workspace = true }
nvui-derive = { path = "../derive" }
tracing = { workspace = true }

[dev-dependencies]
smol = "2"
assertables = "9"
