[workspace]
members = [
  "crates/*"
]
resolver = "3"

[workspace.dependencies]
rmp = "0.8"
rmp-serde = "1"
rmpv = { version = "1", features = ["with-serde"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
dashmap = "6"
flume = "0.12"
arc-swap = "1"
serde_tuple = "1"

[workspace.package]
version = "0.1.0"
edition = "2024"
