[workspace]
members = [
	"crates/derive",
	"crates/nvim-client",
	"crates/nvui-common",
	"crates/nvui",
	"crates/renderer",
]
resolver = "3"

[workspace.dependencies]
renderer = { package = "nvui-renderer", path = "crates/renderer" }
nvim = { package = "nvui-nvim-client", path = "crates/nvim-client" }
rmp = "0.8"
rmp-serde = "1"
rmpv = { version = "1", features = ["with-serde"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
dashmap = "6"
flume = "0.12"
arc-swap = "1"
serde_tuple = "1"
winit = "0.30"
wgpu = "28"
raw-window-handle = "0.6"
smol = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[workspace.package]
version = "0.1.0"
edition = "2024"
