[package]
name = "nvui"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
renderer = { workspace = true }
nvim_client = { workspace = true }
smol = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
thiserror = { workspace = true }
dashmap = { workspace = true }
